export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const ACCESS_TOKEN_ERROR = "ACCESS_TOKEN_ERROR";
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//PROFILE REDUCER
export const AUTH_USER_LOAD = "AUTH_USER_LOAD";
export const AUTH_USER_LOAD_ERROR = "AUTH_USER_LOAD_ERROR";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";

// GAME REDUCER
export const GET_GAME_LIST = "GET_GAME_LIST";
export const SELECT_GAME = "SELECT_GAME";
export const CREATE_GAME = "CREATE_GAME";
export const CREATE_GAME_ERROR = "CREATE_GAME_ERROR";

// PLAYER REDUCER
export const GET_PLAYER_DETAILS = "GET_PLAYER_DETAILS";
export const GET_PLAYER_DETAILS_ERROR = "GET_PLAYER_DETAILS_ERROR";
export const GET_PLAYER_LIST = "GET_PLAYER_LIST";
export const CREATE_PLAYER = "CREATE_PLAYER";
export const CREATE_PLAYER_ERROR = "CREATE_PLAYER_ERROR";
export const UPDATE_PLAYER = "UPDATE_PLAYER";
export const UPDATE_PLAYER_ERROR = "UPDATE_PLAYER_ERROR";
export const DELETE_PLAYER = "DELETE_PLAYER";
export const DELETE_PLAYER_ERROR = "DELETE_PLAYER_ERROR";

// ADMIN REDUCER
export const GET_ADMIN_LIST = "GET_ADMIN_LIST";
export const CREATE_ADMIN = "CREATE_ADMIN";
export const CREATE_ADMIN_ERROR = "CREATE_ADMIN_ERROR";
export const UPDATE_ADMIN = "UPDATE_ADMIN";
export const UPDATE_ADMIN_ERROR = "UPDATE_ADMIN_ERROR";
export const DELETE_ADMIN = "DELETE_ADMIN";
export const DELETE_ADMIN_ERROR = "DELETE_ADMIN_ERROR";

// MATCH REDUCER
export const GET_MATCH_LIST = "GET_MATCH_LIST";
export const CREATE_MATCH = "CREATE_MATCH";
export const CREATE_MATCH_ERROR = "CREATE_MATCH_ERROR";
export const UPDATE_MATCH = "UPDATE_MATCH";
export const UPDATE_MATCH_ERROR = "UPDATE_MATCH_ERROR";
export const DELETE_MATCH = "DELETE_MATCH";
export const DELETE_MATCH_ERROR = "DELETE_MATCH_ERROR";

// STREAM REDUCER
export const GET_STREAM_LIST = "GET_STREAM_LIST";
export const CREATE_STREAM = "CREATE_STREAM";
export const CREATE_STREAM_ERROR = "CREATE_STREAM_ERROR";
export const UPDATE_STREAM = "UPDATE_STREAM";
export const UPDATE_STREAM_ERROR = "UPDATE_STREAM_ERROR";
export const DELETE_STREAM = "DELETE_STREAM";
export const DELETE_STREAM_ERROR = "DELETE_STREAM_ERROR";

// BLOG REDUCER
export const GET_BLOG_LIST = "GET_BLOG_LIST";
export const CREATE_BLOG = "CREATE_BLOG";
export const CREATE_BLOG_ERROR = "CREATE_BLOG_ERROR";
export const UPDATE_BLOG = "UPDATE_BLOG";
export const UPDATE_BLOG_ERROR = "UPDATE_BLOG_ERROR";
export const DELETE_BLOG = "DELETE_BLOG";
export const DELETE_BLOG_ERROR = "DELETE_BLOG_ERROR";

// TEAM REDUCER
export const GET_TEAM_DETAILS = "GET_TEAM_DETAILS";
export const GET_TEAM_DETAILS_ERROR = "GET_TEAM_DETAILS_ERROR";
export const GET_TEAM_LIST = "GET_TEAM_LIST";
export const CREATE_TEAM = "CREATE_TEAM";
export const CREATE_TEAM_ERROR = "CREATE_TEAM_ERROR";
export const UPDATE_TEAM = "UPDATE_TEAM";
export const UPDATE_TEAM_ERROR = "UPDATE_TEAM_ERROR";

// CONTACT REDUCER
export const GET_CONTACT_LIST = "GET_CONTACT_LIST";
export const CONTACT_SUBMIT = "CONTACT_SUBMIT";
export const CONTACT_SUBMIT_ERROR = "CONTACT_SUBMIT_ERROR";
