export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const ACCESS_TOKEN_ERROR = "ACCESS_TOKEN_ERROR";
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//PROFILE REDUCER
export const AUTH_USER_LOAD = "AUTH_USER_LOAD";
export const AUTH_USER_LOAD_ERROR = "AUTH_USER_LOAD_ERROR";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const PASSWORD_CHANGED_ERROR = "PASSWORD_CHANGED_ERROR";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";

// LISTING REDUCER
export const GET_LISTING_DETAILS = "GET_LISTING_DETAILS";
export const GET_LISTING_DETAILS_ERROR = "GET_LISTING_DETAILS_ERROR";
export const GET_LISTING_SEARCH = "GET_LISTING_SEARCH";
export const GET_LISTING_LIST = "GET_LISTING_LIST";
export const GET_FILTER_LISTING = "GET_FILTER_LISTING";
export const GET_MY_LISTING_LIST = "GET_MY_LISTING_LIST";
export const CREATE_LISTING = "CREATE_LISTING";
export const CREATE_LISTING_ERROR = "CREATE_LISTING_ERROR";
export const UPDATE_LISTING = "UPDATE_LISTING";
export const UPDATE_LISTING_ERROR = "UPDATE_LISTING_ERROR";
export const DELETE_LISTING = "DELETE_LISTING";
export const DELETE_LISTING_ERROR = "DELETE_LISTING_ERROR";

// ADMIN REDUCER
export const GET_ADMIN_LIST = "GET_ADMIN_LIST";
export const CREATE_ADMIN = "CREATE_ADMIN";
export const CREATE_ADMIN_ERROR = "CREATE_ADMIN_ERROR";
export const UPDATE_ADMIN = "UPDATE_ADMIN";
export const UPDATE_ADMIN_ERROR = "UPDATE_ADMIN_ERROR";
export const DELETE_ADMIN = "DELETE_ADMIN";
export const DELETE_ADMIN_ERROR = "DELETE_ADMIN_ERROR";

// CATEGORY REDUCER
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";

// USERS REDUCER
export const GET_USERS_LIST = "GET_USERS_LIST";
export const GET_USERS_DETAILS = "GET_USERS_DETAILS";
export const CREATE_USERS = "CREATE_USERS";
export const CREATE_USERS_ERROR = "CREATE_USERS_ERROR";
export const UPDATE_USERS = "UPDATE_USERS";
export const UPDATE_USERS_ERROR = "UPDATE_USERS_ERROR";
export const DELETE_USERS = "DELETE_USERS";
export const DELETE_USERS_ERROR = "DELETE_USERS_ERROR";

// CONTACT REDUCER
export const GET_CONTACT_LIST = "GET_CONTACT_LIST";
export const CONTACT_SUBMIT = "CONTACT_SUBMIT";
export const CONTACT_SUBMIT_ERROR = "CONTACT_SUBMIT_ERROR";
